### ISSUE TITLE
デザインパターンお披露目

### ISSUE THREAD

**Issue by rsudo1005** [sudoryota/sp-web#2]
作った2パターンについてこちらで議論します。

**Comment by rsudo1005** [comment]
![2016040811-15](https://user-images.githubusercontent.com/35139550/34614551-32e7af8a-f275-11e7-8567-e282f5cb3e9f.png)
@sudoryota @ryota51831400 できました。

**Comment by ryota51831400** [comment]
@sudoryota @rsudo1005 おれもできたぜ
![wireframe-ja2](https://user-images.githubusercontent.com/35139900/34614598-5c728b7c-f275-11e7-9e33-35df60b52b31.gif)

**Comment by rsudo1005** [comment]
Aで
